# Generated by Django 2.1.7 on 2019-09-20 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
